[versions]
agp = "8.10.0"
annotationJvm = "1.9.1"
[libraries]
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

